module patmo_commons
  implicit none

  integer,parameter::reactionsNumber = 382
  integer,parameter::chemReactionsNumber = 174
  integer,parameter::photoReactionsNumber = 34
  integer,parameter::reverseReactionsNumber = 174
  integer,parameter::chemSpeciesNumber = 81
  integer,parameter::speciesNumber = 83
  integer,parameter::positionTgas = 82
  integer,parameter::positionDummy = 83
  integer,parameter::cellsNumber = 60
  integer,parameter::photoBinsNumber = 11001
  integer,parameter::patmo_idx_33H2SO4 = 1
  integer,parameter::patmo_idx_34CH3SCH3 = 2
  integer,parameter::patmo_idx_32CH3SCH3 = 3
  integer,parameter::patmo_idx_36SO2 = 4
  integer,parameter::patmo_idx_36SO3 = 5
  integer,parameter::patmo_idx_32SO2_1 = 6
  integer,parameter::patmo_idx_33SO2_3 = 7
  integer,parameter::patmo_idx_CH4O3S = 8
  integer,parameter::patmo_idx_32COS = 9
  integer,parameter::patmo_idx_36SO4 = 10
  integer,parameter::patmo_idx_32HSO3 = 11
  integer,parameter::patmo_idx_32CS = 12
  integer,parameter::patmo_idx_32HSO = 13
  integer,parameter::patmo_idx_34SO2 = 14
  integer,parameter::patmo_idx_32H2SO4 = 15
  integer,parameter::patmo_idx_33HSO = 16
  integer,parameter::patmo_idx_36H2SO4 = 17
  integer,parameter::patmo_idx_33CS2 = 18
  integer,parameter::patmo_idx_O3 = 19
  integer,parameter::patmo_idx_O2 = 20
  integer,parameter::patmo_idx_36SO2_1 = 21
  integer,parameter::patmo_idx_34COS = 22
  integer,parameter::patmo_idx_36H2S = 23
  integer,parameter::patmo_idx_34CS = 24
  integer,parameter::patmo_idx_33SO3 = 25
  integer,parameter::patmo_idx_33H2S = 26
  integer,parameter::patmo_idx_32SO2 = 27
  integer,parameter::patmo_idx_34CS2 = 28
  integer,parameter::patmo_idx_32SO4 = 29
  integer,parameter::patmo_idx_36CH3SCH3 = 30
  integer,parameter::patmo_idx_34SO2_3 = 31
  integer,parameter::patmo_idx_32SO3 = 32
  integer,parameter::patmo_idx_34SH = 33
  integer,parameter::patmo_idx_32HSO2 = 34
  integer,parameter::patmo_idx_HO2 = 35
  integer,parameter::patmo_idx_34H2SO4 = 36
  integer,parameter::patmo_idx_34SO = 37
  integer,parameter::patmo_idx_32SH = 38
  integer,parameter::patmo_idx_32SO = 39
  integer,parameter::patmo_idx_33COS = 40
  integer,parameter::patmo_idx_34SO2_1 = 41
  integer,parameter::patmo_idx_33SO2 = 42
  integer,parameter::patmo_idx_34H2S = 43
  integer,parameter::patmo_idx_CO = 44
  integer,parameter::patmo_idx_32SO2_3 = 45
  integer,parameter::patmo_idx_34HSO = 46
  integer,parameter::patmo_idx_32CS2 = 47
  integer,parameter::patmo_idx_H = 48
  integer,parameter::patmo_idx_33SH = 49
  integer,parameter::patmo_idx_33SO = 50
  integer,parameter::patmo_idx_36SO2_3 = 51
  integer,parameter::patmo_idx_O = 52
  integer,parameter::patmo_idx_N = 53
  integer,parameter::patmo_idx_36SO = 54
  integer,parameter::patmo_idx_33SO2_1 = 55
  integer,parameter::patmo_idx_36SH = 56
  integer,parameter::patmo_idx_34S = 57
  integer,parameter::patmo_idx_N2 = 58
  integer,parameter::patmo_idx_36CS2 = 59
  integer,parameter::patmo_idx_36S = 60
  integer,parameter::patmo_idx_36HSO = 61
  integer,parameter::patmo_idx_33CS = 62
  integer,parameter::patmo_idx_33HSO3 = 63
  integer,parameter::patmo_idx_32S = 64
  integer,parameter::patmo_idx_CO2 = 65
  integer,parameter::patmo_idx_36HSO3 = 66
  integer,parameter::patmo_idx_36HSO2 = 67
  integer,parameter::patmo_idx_OH = 68
  integer,parameter::patmo_idx_H2 = 69
  integer,parameter::patmo_idx_33HSO2 = 70
  integer,parameter::patmo_idx_34HSO3 = 71
  integer,parameter::patmo_idx_34HSO2 = 72
  integer,parameter::patmo_idx_32H2S = 73
  integer,parameter::patmo_idx_33S = 74
  integer,parameter::patmo_idx_36CS = 75
  integer,parameter::patmo_idx_34SO4 = 76
  integer,parameter::patmo_idx_H2O = 77
  integer,parameter::patmo_idx_33SO4 = 78
  integer,parameter::patmo_idx_36COS = 79
  integer,parameter::patmo_idx_33CH3SCH3 = 80
  integer,parameter::patmo_idx_34SO3 = 81

  integer,parameter::chemReactionsOffset = 0
  integer,parameter::photoReactionsOffset = chemReactionsNumber
  integer,parameter::reverseReactionsOffset = &
      photoReactionsOffset + photoReactionsNumber

  integer,parameter::neqAll = speciesNumber*cellsNumber
  integer,parameter::maxNameLength = 50

  integer,dimension(photoReactionsNumber)::photoPartnerIndex = (/patmo_idx_36SO2,patmo_idx_36SO2,patmo_idx_36SO2,patmo_idx_36SO3,patmo_idx_32COS,patmo_idx_34SO2,patmo_idx_34SO2,patmo_idx_34SO2,patmo_idx_33CS2,patmo_idx_O3,patmo_idx_O2,patmo_idx_34COS,patmo_idx_36H2S,patmo_idx_33SO3,patmo_idx_33H2S,patmo_idx_32SO2,patmo_idx_32SO2,patmo_idx_32SO2,patmo_idx_34CS2,patmo_idx_32SO3,patmo_idx_34SO,patmo_idx_32SO,patmo_idx_33COS,patmo_idx_33SO2,patmo_idx_33SO2,patmo_idx_33SO2,patmo_idx_34H2S,patmo_idx_32CS2,patmo_idx_33SO,patmo_idx_36SO,patmo_idx_36CS2,patmo_idx_32H2S,patmo_idx_36COS,patmo_idx_34SO3/)

  integer,parameter,dimension(reactionsNumber)::indexReactants2 = (/patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      positionDummy,&
      patmo_idx_N,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO/)
  integer,parameter,dimension(reactionsNumber)::indexReactants1 = (/patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO2,&
      patmo_idx_33HSO2,&
      patmo_idx_34HSO2,&
      patmo_idx_36HSO2,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_O,&
      patmo_idx_N2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_36SO2,&
      patmo_idx_36SO2,&
      patmo_idx_36SO2,&
      patmo_idx_36SO3,&
      patmo_idx_32COS,&
      patmo_idx_34SO2,&
      patmo_idx_34SO2,&
      patmo_idx_34SO2,&
      patmo_idx_33CS2,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_34COS,&
      patmo_idx_36H2S,&
      patmo_idx_33SO3,&
      patmo_idx_33H2S,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_34CS2,&
      patmo_idx_32SO3,&
      patmo_idx_34SO,&
      patmo_idx_32SO,&
      patmo_idx_33COS,&
      patmo_idx_33SO2,&
      patmo_idx_33SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34H2S,&
      patmo_idx_32CS2,&
      patmo_idx_33SO,&
      patmo_idx_36SO,&
      patmo_idx_36CS2,&
      patmo_idx_32H2S,&
      patmo_idx_36COS,&
      patmo_idx_34SO3,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O3,&
      patmo_idx_N,&
      patmo_idx_32SO4,&
      patmo_idx_33SO4,&
      patmo_idx_34SO4,&
      patmo_idx_36SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3/)
  integer,parameter,dimension(reactionsNumber)::indexProducts2 = (/patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      positionDummy,&
      patmo_idx_N,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_N2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_32SO,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_33S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_34S,&
      patmo_idx_H,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_34S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_33S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_32S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_36S,&
      patmo_idx_H,&
      patmo_idx_36S,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2/)
  integer,parameter,dimension(reactionsNumber)::indexProducts3 = (/positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy/)
  integer,parameter,dimension(reactionsNumber)::indexProducts1 = (/patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O3,&
      patmo_idx_N,&
      patmo_idx_32SO4,&
      patmo_idx_33SO4,&
      patmo_idx_34SO4,&
      patmo_idx_36SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_36SO,&
      patmo_idx_36SO2_1,&
      patmo_idx_36SO2_3,&
      patmo_idx_36SO2,&
      patmo_idx_CO,&
      patmo_idx_34SO2_3,&
      patmo_idx_34SO,&
      patmo_idx_34SO2_1,&
      patmo_idx_33CS,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_CO,&
      patmo_idx_36SH,&
      patmo_idx_33SO2,&
      patmo_idx_33SH,&
      patmo_idx_32SO2_3,&
      patmo_idx_32SO,&
      patmo_idx_32SO2_1,&
      patmo_idx_34CS,&
      patmo_idx_32SO2,&
      patmo_idx_34S,&
      patmo_idx_32S,&
      patmo_idx_CO,&
      patmo_idx_33SO2_3,&
      patmo_idx_33SO,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SH,&
      patmo_idx_32CS,&
      patmo_idx_33S,&
      patmo_idx_36S,&
      patmo_idx_36CS,&
      patmo_idx_32SH,&
      patmo_idx_CO,&
      patmo_idx_34SO2,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO2,&
      patmo_idx_33HSO2,&
      patmo_idx_34HSO2,&
      patmo_idx_36HSO2,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_O,&
      patmo_idx_N2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3/)

end module patmo_commons
