module patmo_commons
  implicit none

  integer,parameter::reactionsNumber = 457
  integer,parameter::chemReactionsNumber = 206
  integer,parameter::photoReactionsNumber = 45
  integer,parameter::reverseReactionsNumber = 206
  integer,parameter::chemSpeciesNumber = 94
  integer,parameter::speciesNumber = 96
  integer,parameter::positionTgas = 95
  integer,parameter::positionDummy = 96
  integer,parameter::cellsNumber = 60
  integer,parameter::photoBinsNumber = 11000
  integer,parameter::patmo_idx_32COS = 1
  integer,parameter::patmo_idx_OH = 2
  integer,parameter::patmo_idx_CO2 = 3
  integer,parameter::patmo_idx_32SH = 4
  integer,parameter::patmo_idx_33COS = 5
  integer,parameter::patmo_idx_33SH = 6
  integer,parameter::patmo_idx_34COS = 7
  integer,parameter::patmo_idx_34SH = 8
  integer,parameter::patmo_idx_36COS = 9
  integer,parameter::patmo_idx_36SH = 10
  integer,parameter::patmo_idx_O = 11
  integer,parameter::patmo_idx_CO = 12
  integer,parameter::patmo_idx_32SO = 13
  integer,parameter::patmo_idx_33SO = 14
  integer,parameter::patmo_idx_34SO = 15
  integer,parameter::patmo_idx_36SO = 16
  integer,parameter::patmo_idx_32CS2 = 17
  integer,parameter::patmo_idx_32CS = 18
  integer,parameter::patmo_idx_33CS2 = 19
  integer,parameter::patmo_idx_33CS = 20
  integer,parameter::patmo_idx_34CS2 = 21
  integer,parameter::patmo_idx_34CS = 22
  integer,parameter::patmo_idx_36CS2 = 23
  integer,parameter::patmo_idx_36CS = 24
  integer,parameter::patmo_idx_32S = 25
  integer,parameter::patmo_idx_33S = 26
  integer,parameter::patmo_idx_34S = 27
  integer,parameter::patmo_idx_36S = 28
  integer,parameter::patmo_idx_32S2 = 29
  integer,parameter::patmo_idx_33S2 = 30
  integer,parameter::patmo_idx_34S2 = 31
  integer,parameter::patmo_idx_36S2 = 32
  integer,parameter::patmo_idx_32SCSOH = 33
  integer,parameter::patmo_idx_33SCSOH = 34
  integer,parameter::patmo_idx_34SCSOH = 35
  integer,parameter::patmo_idx_36SCSOH = 36
  integer,parameter::patmo_idx_O2 = 37
  integer,parameter::patmo_idx_32HSO2 = 38
  integer,parameter::patmo_idx_33HSO2 = 39
  integer,parameter::patmo_idx_34HSO2 = 40
  integer,parameter::patmo_idx_36HSO2 = 41
  integer,parameter::patmo_idx_O3 = 42
  integer,parameter::patmo_idx_32CS2E = 43
  integer,parameter::patmo_idx_M = 44
  integer,parameter::patmo_idx_33CS2E = 45
  integer,parameter::patmo_idx_34CS2E = 46
  integer,parameter::patmo_idx_36CS2E = 47
  integer,parameter::patmo_idx_32SO2 = 48
  integer,parameter::patmo_idx_33SO2 = 49
  integer,parameter::patmo_idx_34SO2 = 50
  integer,parameter::patmo_idx_36SO2 = 51
  integer,parameter::patmo_idx_32H2S = 52
  integer,parameter::patmo_idx_H2O = 53
  integer,parameter::patmo_idx_33H2S = 54
  integer,parameter::patmo_idx_34H2S = 55
  integer,parameter::patmo_idx_36H2S = 56
  integer,parameter::patmo_idx_H = 57
  integer,parameter::patmo_idx_H2 = 58
  integer,parameter::patmo_idx_HO2 = 59
  integer,parameter::patmo_idx_32HSO = 60
  integer,parameter::patmo_idx_33HSO = 61
  integer,parameter::patmo_idx_34HSO = 62
  integer,parameter::patmo_idx_36HSO = 63
  integer,parameter::patmo_idx_32SO3 = 64
  integer,parameter::patmo_idx_33SO3 = 65
  integer,parameter::patmo_idx_34SO3 = 66
  integer,parameter::patmo_idx_36SO3 = 67
  integer,parameter::patmo_idx_32HSO3 = 68
  integer,parameter::patmo_idx_33HSO3 = 69
  integer,parameter::patmo_idx_34HSO3 = 70
  integer,parameter::patmo_idx_36HSO3 = 71
  integer,parameter::patmo_idx_32SO4 = 72
  integer,parameter::patmo_idx_33SO4 = 73
  integer,parameter::patmo_idx_34SO4 = 74
  integer,parameter::patmo_idx_36SO4 = 75
  integer,parameter::patmo_idx_32H2SO4 = 76
  integer,parameter::patmo_idx_33H2SO4 = 77
  integer,parameter::patmo_idx_34H2SO4 = 78
  integer,parameter::patmo_idx_36H2SO4 = 79
  integer,parameter::patmo_idx_32CH3SCH3 = 80
  integer,parameter::patmo_idx_33CH3SCH3 = 81
  integer,parameter::patmo_idx_34CH3SCH3 = 82
  integer,parameter::patmo_idx_36CH3SCH3 = 83
  integer,parameter::patmo_idx_CH4O3S = 84
  integer,parameter::patmo_idx_32SO2_1 = 85
  integer,parameter::patmo_idx_33SO2_1 = 86
  integer,parameter::patmo_idx_34SO2_1 = 87
  integer,parameter::patmo_idx_36SO2_1 = 88
  integer,parameter::patmo_idx_32SO2_3 = 89
  integer,parameter::patmo_idx_33SO2_3 = 90
  integer,parameter::patmo_idx_34SO2_3 = 91
  integer,parameter::patmo_idx_36SO2_3 = 92
  integer,parameter::patmo_idx_N2 = 93
  integer,parameter::patmo_idx_N = 94

  integer,parameter::chemReactionsOffset = 0
  integer,parameter::photoReactionsOffset = chemReactionsNumber
  integer,parameter::reverseReactionsOffset = &
      photoReactionsOffset + photoReactionsNumber

  integer,parameter::neqAll = speciesNumber*cellsNumber
  integer,parameter::maxNameLength = 50

  integer,dimension(photoReactionsNumber)::photoPartnerIndex = (/patmo_idx_32COS,&
      patmo_idx_OH,&
      patmo_idx_CO2,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_36CS2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_33SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_34SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_36SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32H2S,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_H2,&
      patmo_idx_HO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_N2/)

  integer,parameter,dimension(reactionsNumber)::indexReactants1 = (/patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32SCSOH,&
      patmo_idx_33SCSOH,&
      patmo_idx_34SCSOH,&
      patmo_idx_36SCSOH,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS2E,&
      patmo_idx_33CS2E,&
      patmo_idx_34CS2E,&
      patmo_idx_36CS2E,&
      patmo_idx_32CS2E,&
      patmo_idx_33CS2E,&
      patmo_idx_34CS2E,&
      patmo_idx_36CS2E,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S2,&
      patmo_idx_33S2,&
      patmo_idx_34S2,&
      patmo_idx_36S2,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO2,&
      patmo_idx_33HSO2,&
      patmo_idx_34HSO2,&
      patmo_idx_36HSO2,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_O,&
      patmo_idx_N2,&
      patmo_idx_32COS,&
      patmo_idx_OH,&
      patmo_idx_CO2,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_36CS2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_33SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_34SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_36SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32H2S,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_H2,&
      patmo_idx_HO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_N2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32S2,&
      patmo_idx_33S2,&
      patmo_idx_34S2,&
      patmo_idx_36S2,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SCSOH,&
      patmo_idx_33SCSOH,&
      patmo_idx_34SCSOH,&
      patmo_idx_36SCSOH,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO4,&
      patmo_idx_33SO4,&
      patmo_idx_34SO4,&
      patmo_idx_36SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_O3,&
      patmo_idx_N/)
  integer,parameter,dimension(reactionsNumber)::indexReactants2 = (/patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32HSO2,&
      patmo_idx_33HSO2,&
      patmo_idx_34HSO2,&
      patmo_idx_36HSO2,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      positionDummy,&
      patmo_idx_N/)
  integer,parameter,dimension(reactionsNumber)::indexReactants3 = (/positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy/)
  integer,parameter,dimension(reactionsNumber)::indexProducts1 = (/patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO2,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32S2,&
      patmo_idx_33S2,&
      patmo_idx_34S2,&
      patmo_idx_36S2,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SCSOH,&
      patmo_idx_33SCSOH,&
      patmo_idx_34SCSOH,&
      patmo_idx_36SCSOH,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO4,&
      patmo_idx_33SO4,&
      patmo_idx_34SO4,&
      patmo_idx_36SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_O3,&
      patmo_idx_N,&
      patmo_idx_CO,&
      patmo_idx_O,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32CS,&
      patmo_idx_32CS2E,&
      patmo_idx_33CS,&
      patmo_idx_33CS2E,&
      patmo_idx_34CS,&
      patmo_idx_34CS2E,&
      patmo_idx_36CS,&
      patmo_idx_36CS2E,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_32SO,&
      patmo_idx_32SO2_1,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO,&
      patmo_idx_33SO2_1,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO,&
      patmo_idx_34SO2_1,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO,&
      patmo_idx_36SO2_1,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SH,&
      patmo_idx_OH,&
      patmo_idx_H2,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_H,&
      patmo_idx_OH,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_N,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32CS2,&
      patmo_idx_33CS2,&
      patmo_idx_34CS2,&
      patmo_idx_36CS2,&
      patmo_idx_32SCSOH,&
      patmo_idx_33SCSOH,&
      patmo_idx_34SCSOH,&
      patmo_idx_36SCSOH,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS,&
      patmo_idx_33CS,&
      patmo_idx_34CS,&
      patmo_idx_36CS,&
      patmo_idx_32CS2E,&
      patmo_idx_33CS2E,&
      patmo_idx_34CS2E,&
      patmo_idx_36CS2E,&
      patmo_idx_32CS2E,&
      patmo_idx_33CS2E,&
      patmo_idx_34CS2E,&
      patmo_idx_36CS2E,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32H2S,&
      patmo_idx_33H2S,&
      patmo_idx_34H2S,&
      patmo_idx_36H2S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_32S2,&
      patmo_idx_33S2,&
      patmo_idx_34S2,&
      patmo_idx_36S2,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_32HSO2,&
      patmo_idx_33HSO2,&
      patmo_idx_34HSO2,&
      patmo_idx_36HSO2,&
      patmo_idx_32HSO3,&
      patmo_idx_33HSO3,&
      patmo_idx_34HSO3,&
      patmo_idx_36HSO3,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_32H2SO4,&
      patmo_idx_33H2SO4,&
      patmo_idx_34H2SO4,&
      patmo_idx_36H2SO4,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32CH3SCH3,&
      patmo_idx_33CH3SCH3,&
      patmo_idx_34CH3SCH3,&
      patmo_idx_36CH3SCH3,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_1,&
      patmo_idx_33SO2_1,&
      patmo_idx_34SO2_1,&
      patmo_idx_36SO2_1,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_32SO2_3,&
      patmo_idx_33SO2_3,&
      patmo_idx_34SO2_3,&
      patmo_idx_36SO2_3,&
      patmo_idx_O,&
      patmo_idx_N2/)
  integer,parameter,dimension(reactionsNumber)::indexProducts2 = (/patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32HSO2,&
      patmo_idx_33HSO2,&
      patmo_idx_34HSO2,&
      patmo_idx_36HSO2,&
      patmo_idx_32S,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_CO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      patmo_idx_32HSO,&
      patmo_idx_33HSO,&
      patmo_idx_34HSO,&
      patmo_idx_36HSO,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_32SO3,&
      patmo_idx_33SO3,&
      patmo_idx_34SO3,&
      patmo_idx_36SO3,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_CH4O3S,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32SO,&
      patmo_idx_33SO,&
      patmo_idx_34SO,&
      patmo_idx_36SO,&
      positionDummy,&
      patmo_idx_N,&
      patmo_idx_32S,&
      patmo_idx_H,&
      patmo_idx_O,&
      patmo_idx_33S,&
      patmo_idx_34S,&
      patmo_idx_36S,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_32S,&
      positionDummy,&
      patmo_idx_33S,&
      positionDummy,&
      patmo_idx_34S,&
      positionDummy,&
      patmo_idx_36S,&
      positionDummy,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O,&
      positionDummy,&
      positionDummy,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_N,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_H,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_HO2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O3,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      patmo_idx_H2O,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_O,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_O2,&
      patmo_idx_32SO2,&
      patmo_idx_33SO2,&
      patmo_idx_34SO2,&
      patmo_idx_36SO2,&
      patmo_idx_O2,&
      positionDummy/)
  integer,parameter,dimension(reactionsNumber)::indexProducts3 = (/positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32SH,&
      patmo_idx_33SH,&
      patmo_idx_34SH,&
      patmo_idx_36SH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      patmo_idx_OH,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_32COS,&
      patmo_idx_33COS,&
      patmo_idx_34COS,&
      patmo_idx_36COS,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      patmo_idx_M,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy,&
      positionDummy/)

end module patmo_commons
